In [2]:
# Loading the dataset using pandas
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.shape

(3900, 17)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 1 to 3900
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     3900 non-null   int64
 1   Gender                  3900 non-null   str
 2   Item Purchased          3900 non-null   str
 3   Category                3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   int64
 5   Location                3900 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           3863 non-null   float64
 10  Subscription Status     3900 non-null   str
 11  Shipping Type           3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Promo Code Used         3900 non-null   str
 14  Previous Purchases      3900 non-null   int64
 15  Payment Method          3900 non-null   str
 16  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(3), str(13)
memory usage: 518.1 KB

In [26]:
df.isnull().sum()

Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df.dtypes

Customer ID                 int64
Age                         int64
Gender                        str
Item Purchased                str
Category                      str
Purchase Amount (USD)       int64
Location                      str
Size                          str
Color                         str
Season                        str
Review Rating             float64
Subscription Status           str
Shipping Type                 str
Discount Applied              str
Promo Code Used               str
Previous Purchases          int64
Payment Method                str
Frequency of Purchases        str
dtype: object

In [6]:
df.describe()

               Age  Purchase Amount (USD)  Review Rating  Previous Purchases
count  3900.000000            3900.000000    3863.000000         3900.000000
mean     44.068462              59.764359       3.750065           25.351538
std      15.207589              23.685392       0.716983           14.447125
min      18.000000              20.000000       2.500000            1.000000
25%      31.000000              39.000000       3.100000           13.000000
50%      44.000000              60.000000       3.800000           25.000000
75%      57.000000              81.000000       4.400000           38.000000
max      70.000000             100.000000       5.000000           50.000000

In [3]:
# Filling missing Review Rating values with median rating of their respective Category
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [5]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [4]:
# Renaming the columns into snake case format for easy documentation
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [5]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [5]:
# Creating a new column called "generation"
bins = [14, 30, 46, 62, 81] # Defines age threshold
labels = ["Gen Z", "Millenials", "Gen X", "Boomers"] # Defines the labels for each age category

# Creating the generation column
# 'right=False' makes intervals inclusive of left edge and exclusive of right edge [14, 30) -- Gen Z is of the age 14 to 29 yrs
df["generation"] = pd.cut(df["age"], bins=bins, labels=labels, right=False)

In [6]:
# Checking the column 'generation' created
df[["age","generation"]].sample(50)

      age  generation
3416   25       Gen Z
1957   68     Boomers
1515   39  Millenials
12     61       Gen X
3328   42  Millenials
722    27       Gen Z
2456   59       Gen X
3616   42  Millenials
1317   28       Gen Z
1592   56       Gen X
1011   43  Millenials
3690   24       Gen Z
2108   54       Gen X
3610   18       Gen Z
867    37  Millenials
3361   47       Gen X
3655   20       Gen Z
1642   18       Gen Z
2463   60       Gen X
368    24       Gen Z
2044   49       Gen X
3486   51       Gen X
3264   28       Gen Z
770    19       Gen Z
1085   25       Gen Z
3830   22       Gen Z
1763   37  Millenials
3882   35  Millenials
511    61       Gen X
3728   62     Boomers
3003   51       Gen X
1857   51       Gen X
2395   62     Boomers
464    23       Gen Z
2129   40  Millenials
3409   24       Gen Z
1771   46       Gen X
3143   68     Boomers
1672   18       Gen Z
2751   27       Gen Z
1781   31  Millenials
132    30  Millenials
239    49       Gen X
3122   23       Gen Z
3081   64     Boomers
1502   37  Millenials
2890   39  Millenials
96     32  Millenials
2735   46       Gen X
1493   70     Boomers

In [7]:
# Creating 'purchase_frequency_days' column
frequency_mapping = {
    "Fortnightly": 14,
    "Weekly": 7,
    "Bi-Weekly": 14,
    "Annually": 365,
    "Quarterly": 90,
    "Monthly": 30,
    "Every 3 Months": 90    
}

df["purchase_frequency_days"] = df['frequency_of_purchases'].map(frequency_mapping)

In [8]:
df[['frequency_of_purchases','purchase_frequency_days']].sample(15)

     frequency_of_purchases  purchase_frequency_days
1404                 Weekly                        7
3778               Annually                      365
2524              Quarterly                       90
2611            Fortnightly                       14
526                 Monthly                       30
1421            Fortnightly                       14
280               Bi-Weekly                       14
2009              Bi-Weekly                       14
524                Annually                      365
1835              Quarterly                       90
2566              Quarterly                       90
3847            Fortnightly                       14
2473              Quarterly                       90
1045              Bi-Weekly                       14
1452              Quarterly                       90

In [11]:
df[["discount_applied","promo_code_used"]].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [10]:
(df["discount_applied"] == df["promo_code_used"]).all()

np.True_

In [9]:
# Drop "promo_code_used" column -- a redundant column
df = df.drop("promo_code_used", axis=1)

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'generation', 'purchase_frequency_days'],
      dtype='str')

In [18]:
# Installing packages to allow connecting PostgreSQL and Jupyter notebook
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.1.3-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\VINCENT\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.4 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.9 MB 2.0 MB/s eta 0:00:01
   -------------------------------- ------- 2.4/2.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 3.5 MB/s  0:00:01
Downloading sqlalchemy-2.1.3-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 2.4/2.4 MB 16.9 MB/s  0:00:00
Installing collected packages: sqlalchemy, psycopg2-binary

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.13 sqlalchemy-2.1.3

In [10]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username = "postgres"
password = "01871"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name =  "customer"
df.to_sql(table_name, engine, if_exists="replace",index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'")

Data successfully loaded into table 'customer' in database 'customer_behaviour'

In [18]:
import sys

print(sys.executable)
print(sys.version)

C:\Users\VINCENT\.conda\envs\virtual_env\python.exe
3.14.8 | packaged by Anaconda, Inc. | (main, Oct  1 2026, 20:25:10) [MSC v.1942 64 bit (AMD64)]

In [19]:
import psycopg2

ImportError: DLL load failed while importing _psycopg: An Application Control policy has blocked this file.

In [20]:
%pip show psycopg2-binary

Name: psycopg2-binary
Version: 2.9.13
Summary: psycopg2 - Python-PostgreSQL Database Adapter
Home-page: https://psycopg.org/
Author: Federico Di Gregorio
Author-email: fog@initd.org
License: LGPL with exceptions
Location: C:\Users\VINCENT\.conda\envs\virtual_env\Lib\site-packages
Requires:
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [21]:
%pip show sqlalchemy

Name: SQLAlchemy
Version: 2.1.3
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author:
Author-email: Mike Bayer <mike_mp@zzzcomputing.com>
License-Expression: MIT
Location: C:\Users\VINCENT\.conda\envs\virtual_env\Lib\site-packages
Requires: typing-extensions
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [1]:
import psycopg2

print(psycopg2.__version__)

2.9.12 (dt dec pq3 ext lo64)